name: 'push on server'
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: "set ssh keys"
        run:    |
          sudo mkdir -p ~/.ssh
          sudo echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: "deploy to server"
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
              cd apps
              cd nikoloz-gogua-movie-quotes-front
              git pull
              npm ci
              npm run build
          EOF
        
           
         
